// src/Sponsors.tsx
import { useCallback, useEffect, useState } from "react";
import { CONFIG } from "./config";
import { DisplaySettingsState } from "./baseball/model/DisplaySettingsState";

type Props = {
  sponsors: string[],
  displaySettings: DisplaySettingsState
}

export const Sponsors = ({ sponsors, displaySettings }: Props) => {
  const getRandomSponsor = useCallback(() => sponsors[Math.floor(Math.random() * sponsors.length)], [sponsors]);
  const [currentSponsor, setCurrentSponsor] = useState<string>(getRandomSponsor());

  useEffect(() => {
    const intervalId = setInterval(() => {
      setCurrentSponsor(getRandomSponsor);
    }, CONFIG.sponsorInterval);

    return () => clearInterval(intervalId);
  }, [sponsors, getRandomSponsor, setCurrentSponsor]);

  const backgroundGradient = displaySettings.backgroundGradient;
  const layoutGradient = displaySettings.layoutGradient;

  return (<div style={{
    height: "208px",
    width: "340px",
    border: `${CONFIG.borderSize} solid ${CONFIG.borderColor}`,
    background: `linear-gradient(${backgroundGradient.angle}deg, ${backgroundGradient.startColor}ff ${backgroundGradient.startPercentage}%, ${backgroundGradient.endColor}ff ${backgroundGradient.endPercentage}%)`,
    display: "flex",
    flexDirection: "column"
  }}>
    <div style={{
      background: `linear-gradient(${layoutGradient.angle}deg, ${layoutGradient.startColor}ff ${layoutGradient.startPercentage}%, ${layoutGradient.endColor}ff ${layoutGradient.endPercentage}%)`,
      fontFamily: `${displaySettings.font?.name}`,
      color: `${displaySettings.fontColorDark}`,
      fontSize: "24px",
      textAlign: "center"
    }}>
      Hard Bulls are sponsored by
    </div>
    <div style={{display: "flex", justifyContent: "center", height: `calc(208px - 34px - ${CONFIG.borderSize})`, padding: CONFIG.borderSize }}>
      <img src={currentSponsor} alt="Sponsor" style={{
        objectFit: "contain",
        backgroundColor: "#ffffff",
        height: "100%",
        width: "100%"
      }} />
    </div>
  </div>);
};

// src/web-components/sponsors-component.ts
import { Gradient } from "../model/Gradient"

export class SponsorsComponent extends HTMLElement {
    private container: HTMLDivElement = document.createElement("div")
    private titleElement: HTMLDivElement = document.createElement("div")
    private imageContainerElement: HTMLDivElement = document.createElement("div")
    private imageElement: HTMLImageElement = document.createElement("img")
    private clearIntervalId?: number
    private componentHeight: number = 208

    connectedCallback() {
        const shadow = this.attachShadow({ mode: "open" })

        this.container.style.borderStyle = "solid"
        this.container.style.display = "flex"
        this.container.style.flexDirection = "column"
        this.container.style.height = `${this.componentHeight}px`
        this.container.style.width = "340px"

        this.titleElement.style.textAlign = "center"
        this.titleElement.style.fontSize = "24px"

        this.imageContainerElement.style.display = "flex"
        this.imageContainerElement.style.justifyContent = "center"
        this.imageContainerElement.style.height = `calc(${this.componentHeight}px - ${this.titleElementHeightOffset()})`
        this.imageContainerElement.style.padding = "0"

        this.imageElement.style.objectFit = "contain"
        this.imageElement.style.backgroundColor = "#ffffff" // todo blur oder detect best background color
        this.imageElement.style.height = "100%"
        this.imageElement.style.width = "100%"
        this.imageElement.alt = "Sponsor"

        this.imageContainerElement.append(this.imageElement)

        this.container.append(this.titleElement, this.imageContainerElement)

        shadow.append(this.container)
    }

    public updateSponsors(sponsors: string[], interval: number) {
        if (this.clearIntervalId) {
            clearInterval(this.clearIntervalId)
        }

        this.clearIntervalId = setInterval(() => {
            this.imageElement.src = sponsors[Math.floor(Math.random() * sponsors.length)]
        }, Math.max(1000, Math.abs(interval)))

        this.imageElement.src = sponsors[Math.floor(Math.random() * sponsors.length)]
    }

    set fontLineHeight(fontLineHeight: number) {
        this.titleElement.style.lineHeight = fontLineHeight.toString()
    }

    set borderColor(color: string) {
        this.container.style.borderColor = color
    }

    set borderSize(size: string) {
        this.container.style.borderWidth = size
        this.container.style.height = `calc(${this.container}px - ${size} - ${size})`

        this.imageContainerElement.style.height = `calc(${this.componentHeight}px - ${this.titleElementHeightOffset()})`
        this.imageContainerElement.style.paddingTop = size
    }

    set fontColor(color: string) {
        this.titleElement.style.color = color
    }

    set fontName(name: string) {
        this.container.style.fontFamily = name
    }

    set backgroundGradient(gradient: Gradient) {
        this.container.style.background = `linear-gradient(${gradient.angle}deg, ${gradient.startColor}ff ${gradient.startPercentage}%, ${gradient.endColor}ff ${gradient.endPercentage}%)`
    }

    set layoutGradient(gradient: Gradient) {
        this.titleElement.style.background = `linear-gradient(${gradient.angle}deg, ${gradient.startColor}ff ${gradient.startPercentage}%, ${gradient.endColor}ff ${gradient.endPercentage}%)`
    }

    set sponsorsTitle(title: string) {
        this.titleElement.textContent = title
        this.imageContainerElement.style.height = `calc(208px - ${this.titleElementHeightOffset()})`
    }

    private titleElementHeightOffset(): string {
        return `(${this.titleElement.offsetHeight}px`
    }
}
